In [36]:
import pandas as pd

In [37]:
df = pd.read_csv("../data/raw/export-tranzactii-2022-sector-2.csv", sep=";")

In [38]:
df.head()

,tip,Tip strada,Denumire strada,Zona,S utila,S desfasurata,S teren,Pret tranzactie LEI,an_constructie,Perioada tranzactie
0,apartament,Alee,BISTRICIOARA,colentina,91.41,NaN,NaN,469908.0,1989.0,2022-T1
1,apartament,Alee,BISTRICIOARA,colentina,56.44,NaN,NaN,252241.0,1987.0,2022-T1
2,apartament,Alee,BRASOVENI,tei,52.40,NaN,NaN,373347.0,1985.0,2022-T1
3,apartament,Alee,BURIDAVA,colentina,43.56,NaN,NaN,316527.0,2016.0,2022-T1
4,apartament,Alee,CIRCULUI,tei,59.60,NaN,NaN,495000.0,1960.0,2022-T1

In [39]:
df.shape

(4325, 10)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4325 entries, 0 to 4324
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tip                  4325 non-null   str
 1   Tip strada           4325 non-null   str
 2   Denumire strada      4325 non-null   str
 3   Zona                 4325 non-null   str
 4   S utila              3870 non-null   float64
 5   S desfasurata        325 non-null    float64
 6   S teren              139 non-null    float64
 7   Pret tranzactie LEI  4282 non-null   float64
 8   an_constructie       4322 non-null   float64
 9   Perioada tranzactie  4325 non-null   str
dtypes: float64(5), str(5)
memory usage: 338.0 KB

In [41]:
df.describe()

,S utila,S desfasurata,S teren,Pret tranzactie LEI,an_constructie
count,3870.000000,325.000000,139.000000,4.282000e+03,4322.000000
mean,56.457408,76.769938,136.168058,4.395393e+05,1988.432207
std,38.083131,66.462676,291.176404,3.090505e+05,27.119024
min,0.000000,3.500000,0.430000,1.000000e+04,1899.000000
25%,39.067500,45.550000,13.360000,2.570370e+05,1974.000000
50%,51.190000,58.500000,20.540000,3.803040e+05,1983.000000
75%,65.680000,81.000000,169.500000,5.304535e+05,2020.000000
max,1507.560000,578.000000,2367.000000,3.898370e+06,2087.000000

In [42]:
df.isnull().sum()

tip                       0
Tip strada                0
Denumire strada           0
Zona                      0
S utila                 455
S desfasurata          4000
S teren                4186
Pret tranzactie LEI      43
an_constructie            3
Perioada tranzactie       0
dtype: int64

In [43]:
(df.isnull().sum() / len(df) * 100).round(2)

tip                     0.00
Tip strada              0.00
Denumire strada         0.00
Zona                    0.00
S utila                10.52
S desfasurata          92.49
S teren                96.79
Pret tranzactie LEI     0.99
an_constructie          0.07
Perioada tranzactie     0.00
dtype: float64

In [44]:
df.duplicated().sum()

np.int64(10)

In [45]:
df[df.duplicated(keep=False)].sort_values(
    by=["Denumire strada", "Pret tranzactie LEI"]
)

,tip,Tip strada,Denumire strada,Zona,S utila,S desfasurata,S teren,Pret tranzactie LEI,an_constructie,Perioada tranzactie
154,apartament,Strada,BAICULUI,colentina,59.06,NaN,NaN,375714.0,1990.0,2022-T1
2485,apartament,Strada,BAICULUI,colentina,59.06,NaN,NaN,375714.0,1990.0,2022-T1
62,apartament,Sosea,FABRICA DE GLUCOZA,pipera sud,NaN,45.7,NaN,338243.0,2020.0,2022-T1
1334,apartament,Sosea,FABRICA DE GLUCOZA,pipera sud,NaN,45.7,NaN,338243.0,2020.0,2022-T1
103,apartament,Sosea,IANCULUI,vatra luminoasa,45.60,NaN,NaN,434720.0,1977.0,2022-T1
1552,apartament,Sosea,IANCULUI,vatra luminoasa,45.60,NaN,NaN,434720.0,1977.0,2022-T1
133,apartament,Sosea,PIPERA,pipera sud,84.10,NaN,NaN,727049.0,2020.0,2022-T1
2178,apartament,Sosea,PIPERA,pipera sud,84.10,NaN,NaN,727049.0,2020.0,2022-T1
2229,apartament,Sosea,STEFAN CEL MARE,tei,44.19,NaN,NaN,78040.0,2007.0,2022-T2
2239,apartament,Sosea,STEFAN CEL MARE,tei,44.19,NaN,NaN,78040.0,2007.0,2022-T2
2240,apartament,Sosea,STEFAN CEL MARE,tei,44.19,NaN,NaN,78040.0,2007.0,2022-T2
2233,apartament,Sosea,STEFAN CEL MARE,tei,56.38,NaN,NaN,105323.0,2007.0,2022-T2
2250,apartament,Sosea,STEFAN CEL MARE,tei,56.38,NaN,NaN,105323.0,2007.0,2022-T2
4108,apartament,Strada,"VASILE BACILA, MAIOR",colentina,53.28,NaN,NaN,171011.0,2008.0,2022-T3
4113,apartament,Strada,"VASILE BACILA, MAIOR",colentina,53.28,NaN,NaN,171011.0,2008.0,2022-T3
4114,apartament,Strada,"VASILE BACILA, MAIOR",colentina,53.28,NaN,NaN,171011.0,2008.0,2022-T3
306,apartament,Strada,"VISARION SACHELARIE, LOCOTENENT",iancului,90.08,NaN,NaN,954142.0,2020.0,2022-T1
4225,apartament,Strada,"VISARION SACHELARIE, LOCOTENENT",iancului,90.08,NaN,NaN,954142.0,2020.0,2022-T1

In [46]:
df["tip"].value_counts()

tip
apartament    3987
casa           250
teren           60
comercial       28
Name: count, dtype: int64

In [47]:
apartments = df[df["tip"] == "apartament"]

In [48]:
apartments["Zona"].value_counts()

Zona
centrala           841
pantelimon         717
tei                687
pipera sud         620
colentina          555
iancului           249
vatra luminoasa    117
floreasca           98
andronache          40
Colentina           27
ion creanga         19
-                   15
Tei                  2
Name: count, dtype: int64

In [49]:
apartments[
    (apartments["an_constructie"] > 2022) |
    (apartments["an_constructie"] < 1900)
][["Zona", "Denumire strada", "an_constructie"]]

           Zona            Denumire strada  an_constructie
259    centrala                    PASULUI          1899.0
723    centrala  EMANUEL PAKE-PROTOPOPESCU          1899.0
3142   centrala   IANCU CAVALER DE FLONDOR          1899.0
3510          -          NICOLAE FILIPESCU          1899.0
4166  colentina           VASILE STOLNICUL          2087.0

In [50]:
apartments[
    (apartments["S utila"] <= 10) |
    (apartments["S utila"] > 300)
][
    ["Zona", "Denumire strada", "S utila", "Pret tranzactie LEI", "an_constructie"]
].sort_values("S utila")

,Zona,Denumire strada,S utila,Pret tranzactie LEI,an_constructie
4035,centrala,TRAIAN,3.20,NaN,1940.0
1028,colentina,COLENTINA,3.34,457764.0,2000.0
3550,centrala,ORZARI,3.40,545450.0,2020.0
1030,colentina,COLENTINA,3.41,566513.0,2013.0
3387,centrala,MARIA ROSETTI,4.00,345342.0,1935.0
637,centrala,CAROL I,4.55,42039.0,1995.0
1025,colentina,COLENTINA,4.65,666242.0,2008.0
1335,pipera sud,FABRICA DE GLUCOZA,4.75,384948.0,2020.0
1336,pipera sud,FABRICA DE GLUCOZA,4.76,365606.0,2020.0
289,centrala,TIMPULUI,5.25,556256.0,1932.0
2412,centrala,AUSTRULUI,5.40,514030.0,1935.0
4283,centrala,ZECE MESE,6.03,690000.0,1936.0
4045,centrala,TUNARI,6.28,NaN,1943.0
2747,centrala,"DAVID PRAPORGESCU, GENERAL",6.87,24604.0,1938.0
2498,centrala,BARBU PARIS MUMULEANU,8.12,450000.0,1940.0
969,centrala,POPA NAN,9.00,331695.0,1936.0
1330,pipera sud,FABRICA DE GLUCOZA,9.01,586875.0,2020.0
4263,floreasca,WOLFGANG AMADEUS MOZART,9.03,46940.0,1960.0
2924,Colentina,FABRICA DE GHEATA,9.27,589050.0,2017.0
96,pipera sud,FABRICA DE GLUCOZA,506.11,2719200.0,2022.0
3859,floreasca,SERGHEI VASILIEVICI RAHMANINOV,520.00,NaN,2020.0

In [51]:
apartments["S utila"].quantile(
    [0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

0.01     14.3422
0.05     24.0080
0.25     39.6050
0.50     51.1800
0.75     65.3050
0.95     96.6090
0.99    141.3808
Name: S utila, dtype: float64

In [52]:
apartments = apartments.copy()

apartments["pret_per_sqm"] = (
    apartments["Pret tranzactie LEI"] /
    apartments["S utila"]
)

In [53]:
apartments["pret_per_sqm"].describe()

count      3696.000000
mean       8035.216417
std        7205.801042
min         312.500000
25%        5929.917167
50%        7191.738949
75%        8917.530597
max      166132.844575
Name: pret_per_sqm, dtype: float64

In [54]:
apartments[
    [
        "Zona",
        "Denumire strada",
        "S utila",
        "Pret tranzactie LEI",
        "pret_per_sqm",
        "an_constructie"
    ]
].sort_values(
    "pret_per_sqm",
    ascending=False
).head(10)

,Zona,Denumire strada,S utila,Pret tranzactie LEI,pret_per_sqm,an_constructie
1030,colentina,COLENTINA,3.41,566513.0,166132.844575,2013.0
3550,centrala,ORZARI,3.40,545450.0,160426.470588,2020.0
1025,colentina,COLENTINA,4.65,666242.0,143277.849462,2008.0
1028,colentina,COLENTINA,3.34,457764.0,137055.089820,2000.0
4283,centrala,ZECE MESE,6.03,690000.0,114427.860697,1936.0
289,centrala,TIMPULUI,5.25,556256.0,105953.523810,1932.0
2412,centrala,AUSTRULUI,5.40,514030.0,95190.740741,1935.0
3387,centrala,MARIA ROSETTI,4.00,345342.0,86335.500000,1935.0
1335,pipera sud,FABRICA DE GLUCOZA,4.75,384948.0,81041.684211,2020.0
3099,tei,GRIGORE IONESCU,24.59,1977666.0,80425.620171,1985.0